version: "3.9"
services:
  ansible:
    hostname: ansible
    build: ./server
    volumes:
      - ./home:/home/user
      - /etc/localtime:/etc/localtime:ro
      - ./ansible:/etc/ansible

  remote:
    build: remote
    deploy:
       replicas: 3
    volumes:
      - /etc/localtime:/etc/localtime:ro

